"""
Researcher role.
For each cycle:
  1. Ask the LLM for 2 search queries based on what's been collected.
  2. For each query, search for candidate URLs.
  3. Fetch and extract each candidate (up to SOURCES_PER_CYCLE accepted).
  4. Summarise each source with the LLM.
  5. Save each accepted source immediately.
"""
from __future__ import annotations

import logging
import re
import time

import llm_client as llm
import db
import search as search_mod
from fetcher import fetch_and_extract
from prompts import researcher_prompt, search_query_prompt
from config import SOURCES_PER_CYCLE, MIN_RELEVANCE_SCORE, MIN_QUALITY_SCORE, MAX_TEXT_CHARS, resolve_model, RESEARCHER_MODEL

logger = logging.getLogger(__name__)


def _existing_notes_summary(run_id: int) -> str:
    summaries = db.get_all_summaries(run_id)
    if not summaries:
        return ""
    lines = []
    for s in summaries[-10:]:  # last 10 to keep prompt manageable
        lines.append(f"- [{s['title']}]({s['url']}): {s['summary'][:200]}")
    return "\n".join(lines)


def _parse_researcher_response(text: str) -> dict:
    def extract(label: str) -> str:
        pattern = rf"^{label}:\s*(.*?)(?=\n[A-Z_]+:|\Z)"
        m = re.search(pattern, text, re.MULTILINE | re.DOTALL)
        return m.group(1).strip() if m else ""

    def extract_score(label: str) -> int:
        m = re.search(rf"^{label}:\s*(\d+)", text, re.MULTILINE)
        return int(m.group(1)) if m else 0

    return {
        "summary": extract("SUMMARY"),
        "detailed_summary": extract("DETAILED_SUMMARY"),
        "why_relevant": extract("WHY_RELEVANT"),
        "key_points": extract("KEY_POINTS"),
        "quality_score": extract_score("QUALITY_SCORE"),
        "relevance_score": extract_score("RELEVANCE_SCORE"),
    }


def _parse_queries(text: str) -> list[str]:
    queries = []
    for i in (1, 2):
        m = re.search(rf"^QUERY_{i}:\s*(.+)", text, re.MULTILINE)
        if m:
            queries.append(m.group(1).strip())
    return queries



def run_researcher(run_id: int, cycle: int, topic: str, next_angles: str, model: str | None = None) -> int:
    """Run the researcher pass. Returns number of sources successfully accepted."""
    model = resolve_model(model or RESEARCHER_MODEL)
    logger.info("Researcher starting — run=%d cycle=%d model=%s", run_id, cycle, model)

    accepted_urls = db.get_accepted_urls(run_id)
    all_summaries = db.get_all_summaries(run_id)
    previous_titles = [s["title"] for s in all_summaries]
    notes_summary = _existing_notes_summary(run_id)

    # --- Ask LLM for search queries ---
    query_prompt = search_query_prompt(topic, cycle, previous_titles, next_angles)
    try:
        query_response = llm.chat(query_prompt, system=None, model=model)
        queries = _parse_queries(query_response)
    except Exception as exc:
        logger.error("LLM failed to generate queries: %s", exc)
        db.log_failure(run_id, cycle, "query_generation", "", str(exc))
        return 0

    if not queries:
        logger.warning("No queries generated by LLM, using topic directly")
        queries = [topic]

    # --- Search and fetch ---
    accepted_count = 0
    seen_in_this_cycle: set[str] = set()

    for query in queries:
        if accepted_count >= SOURCES_PER_CYCLE:
            break

        logger.info("Searching: %s", query)
        try:
            results = search_mod.search(query, num_results=5)
        except Exception as exc:
            logger.error("Search failed for query %r: %s", query, exc)
            db.log_failure(run_id, cycle, "search", "", str(exc))
            continue

        for result in results:
            if accepted_count >= SOURCES_PER_CYCLE:
                break

            url = result.get("url", "").strip()
            if not url:
                continue
            if url in accepted_urls or url in seen_in_this_cycle:
                logger.info("Skipping duplicate URL: %s", url)
                continue

            seen_in_this_cycle.add(url)

            # --- Get text: use Tavily raw_content if available, else fetch ---
            raw_content = result.get("raw_content", "")
            if raw_content and len(raw_content) >= 200:
                logger.info("Using Tavily raw_content for: %s", url)
                fetched = {"ok": True, "text": raw_content[:MAX_TEXT_CHARS], "title": result.get("title", ""), "error": None}
            else:
                logger.info("Fetching: %s", url)
                fetched = fetch_and_extract(url)
                if not fetched["ok"]:
                    db.log_failure(run_id, cycle, "fetch", url, fetched["error"] or "unknown")
                    continue

            if len(fetched["text"]) < 200:
                logger.info("Skipping thin content: %s", url)
                db.log_failure(run_id, cycle, "thin_content", url, "less than 200 chars")
                continue

            # --- LLM summarise ---
            prompt = researcher_prompt(
                topic=topic,
                source_text=fetched["text"],
                source_url=url,
                source_title=fetched["title"] or result.get("title", ""),
                existing_notes_summary=notes_summary,
            )
            try:
                llm_response = llm.chat(prompt, system=llm.RESEARCHER_SYSTEM, model=model)
                parsed = _parse_researcher_response(llm_response)
            except Exception as exc:
                logger.error("LLM summarisation failed for %s: %s", url, exc)
                db.log_failure(run_id, cycle, "llm_summarise", url, str(exc))
                continue

            relevance = parsed["relevance_score"]
            quality = parsed["quality_score"]

            if relevance < MIN_RELEVANCE_SCORE or quality < MIN_QUALITY_SCORE:
                logger.info(
                    "Source rejected (relevance=%d quality=%d): %s",
                    relevance, quality, url,
                )
                db.log_failure(
                    run_id, cycle, "score_too_low", url,
                    f"relevance={relevance} quality={quality}",
                )
                continue

            # --- Save to DB ---
            source_data = {
                "url": url,
                "title": fetched["title"] or result.get("title", ""),
                "source_name": result.get("source_name", ""),
                "author": "",
                "publish_date": "",
                "extracted_text": fetched["text"],
                "status": "accepted",
                **parsed,
            }
            db.save_source(run_id, cycle, source_data)
            accepted_urls.add(url)
            accepted_count += 1
            logger.info(
                "Source accepted (relevance=%d quality=%d): %s",
                relevance, quality, url,
            )

            # Small delay to be polite
            time.sleep(1)

    logger.info("Researcher done — %d source(s) accepted", accepted_count)
    return accepted_count
